---
driver:
   name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: latest

provisioner:
  data_bag_path: "test/integration/default/data_bags"
  encrypted_data_bag_secret_key_path: "test/integration/default/encrypted_data_bag_secret"

platforms:
- name: centos-6.5
  run_list:
  - recipe[yum]
- name: centos-7.0
  run_list:
  - recipe[yum]
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
- name: ubuntu-14.04
  run_list:
  - recipe[apt]

suites:
- name: default
  attributes:
    ssmtp:
      root: 'user@example.com'
      rewrite_domain: 'example.com'
      mailhub_name: 'localhost'
      mailhub_port: 2525
      from_line_override: true
      credential_method: 'data_bag'
      use_starttls: false
      use_tls: false
  run_list:
  - recipe[ssmtp::default]
  - recipe[minitest-handler]
